version: '3.1'

services:
  mongo:
    image: mongo
    restart: always

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081

  vasya:
    build: .
    restart: always
    environment:
      MONGO_URL: mongodb://mongo:27017/voicy
      USE_WEBHOOK: "false"
    env_file: ".env"
